[package]
name = "investec-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.8"
oauth2 = "4.2.0"
serde = "1.0.138"
serde_json = "1.0.82"
